[build]
  command = "yarn build"
  functions = "functions-build"
  publish = "build"

[[redirects]]
  from = "/api/movies"
  to = "/.netlify/functions/movies"
  status = 301

[[redirects]]
  from = "/api/genres"
  to = "/.netlify/functions/genres"
  status = 301  